server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/just_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: movit
    password: root
#  data:
#    mongodb:
#      database: test
#      port: 27017
#      username: test
#      password: test
#      host: localhost
#      authentication-database: admin
rocketmq:
  name-server: localhost:9876
  producer:
    group: myProGroup